connect_debug_port u_ila_0/probe1 [get_nets [list core_inst/io_uart_rxd]]
connect_debug_port u_ila_0/probe2 [get_nets [list core_inst/io_uart_txd]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list pcie4c_uscale_plus_inst/inst/pcie4c_uscale_plus_0_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/CLK_USERCLK]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[0]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[1]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[2]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[3]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[4]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[5]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[6]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[7]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[8]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[9]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[10]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[11]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[12]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[13]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[14]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[15]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[16]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[17]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[18]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[19]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[20]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[21]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[22]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[23]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[24]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[25]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[26]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[27]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[28]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[29]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[30]} {core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/leds[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/riscv_uart_rxd]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list core_inst/core_inst/core_pcie_inst/core_inst/app.app_block_inst/riscv_uart_txd]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets pcie_user_clk]
